AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoBooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: books
      PrimaryKey:
        Name: id
        Type: String
  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-ejemplo/80bb0af885e5fee7cd955e3551c675a2
      Handler: create-book.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-ejemplo/80bb0af885e5fee7cd955e3551c675a2
      Handler: get-books.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        GetBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
